import os

from flask import (
    Blueprint, render_template, request,
    redirect, url_for, flash, jsonify, current_app, send_file,
)
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename

from .. import db
from ..models import ListaJob
from ..services.listas_service import (
    start_lista_job,
    listas_dir,
    result_path,
    get_live_state,
    request_stop,
    _read_file,
    _read_file_info,
)

bp = Blueprint("listas", __name__, url_prefix="/listas")

ALLOWED_EXT = {"csv", "xlsx"}


def _allowed(filename: str) -> bool:
    return "." in filename and filename.rsplit(".", 1)[1].lower() in ALLOWED_EXT


# ── main page ──────────────────────────────────────────────────────────────────

@bp.route("")
@login_required
def listas_page():
    user_id = current_user.id
    d = listas_dir(user_id)

    upload_files = []
    for fn in sorted(os.listdir(d)):
        if not fn.lower().endswith((".csv", ".xlsx")):
            continue
        # Skip output files generated by jobs
        if any(fn.startswith(f"job_") for part in [fn] if "_" in fn):
            if fn.startswith("job_"):
                continue
        if fn.startswith("checkpoint_"):
            continue
        path = os.path.join(d, fn)
        try:
            columns, row_count = _read_file_info(path)
        except Exception:
            row_count = 0
            columns = []
        upload_files.append({
            "name": fn,
            "row_count": row_count,
            "columns": columns,
            "size_kb": round(os.path.getsize(path) / 1024, 1),
        })

    # Recent jobs for this user (last 10)
    jobs = (ListaJob.query
            .filter_by(user_id=user_id)
            .order_by(ListaJob.created_at.desc())
            .limit(10)
            .all())

    return render_template("listas.html", upload_files=upload_files, jobs=jobs)


# ── file management ────────────────────────────────────────────────────────────

@bp.route("/upload", methods=["POST"])
@login_required
def upload_file():
    f = request.files.get("lista_file")
    if not f or not f.filename or not _allowed(f.filename):
        flash("Arquivo inválido. Envie um .csv ou .xlsx.", "error")
        return redirect(url_for("listas.listas_page"))
    fn = secure_filename(f.filename)
    f.save(os.path.join(listas_dir(current_user.id), fn))
    flash(f"Arquivo '{fn}' enviado.", "success")
    return redirect(url_for("listas.listas_page"))


@bp.route("/file/<filename>/delete", methods=["POST"])
@login_required
def delete_file(filename):
    fn = secure_filename(filename)
    path = os.path.join(listas_dir(current_user.id), fn)
    if os.path.exists(path):
        os.remove(path)
        flash(f"Arquivo '{fn}' removido.", "success")
    return redirect(url_for("listas.listas_page"))


@bp.route("/file/<filename>/columns")
@login_required
def file_columns(filename):
    fn = secure_filename(filename)
    path = os.path.join(listas_dir(current_user.id), fn)
    if not os.path.exists(path):
        return jsonify({"error": "not found"}), 404
    try:
        columns, _ = _read_file_info(path)
        rows, _ = _read_file(path)
        preview = rows[:2]
        return jsonify({"columns": columns, "preview": preview})
    except Exception as exc:
        return jsonify({"error": str(exc)}), 500


# ── start job ──────────────────────────────────────────────────────────────────

@bp.route("/start", methods=["POST"])
@login_required
def start_job():
    try:
        data = request.get_json(silent=True) or {}

        filename     = (data.get("filename")     or "").strip()
        phone_column = (data.get("phone_column") or "").strip()
        mode         = (data.get("mode")         or "dedup_validate").strip()
        _w           = data.get("max_workers")
        try:
            max_workers = max(1, min(int(_w), 100)) if _w is not None else 10
        except (ValueError, TypeError):
            max_workers = 10

        if not filename or not phone_column:
            return jsonify({"error": "Campos obrigatórios faltando."}), 400

        if mode not in ("dedup_only", "dedup_validate"):
            return jsonify({"error": "Modo inválido."}), 400

        fn = secure_filename(filename)
        if not os.path.exists(os.path.join(listas_dir(current_user.id), fn)):
            return jsonify({"error": "Arquivo não encontrado."}), 404

        job_id = start_lista_job(
            current_app._get_current_object(),
            current_user.id,
            fn,
            phone_column,
            max_workers,
            mode,
        )
        return jsonify({"job_id": job_id})
    except Exception as exc:
        return jsonify({"error": f"Erro interno: {exc}"}), 500


# ── job status ─────────────────────────────────────────────────────────────────

@bp.route("/job/<int:job_id>/status")
@login_required
def job_status(job_id):
    live = get_live_state(job_id)
    if live:
        total    = live["total"]
        has_wa   = live["has_wa"]
        no_wa    = live["no_wa"]
        errors   = live["errors"]
        status   = live["status"]
        mode     = live["mode"]
        last_msg = live["last_message"]
    else:
        job = db.session.get(ListaJob, job_id)
        if not job or job.user_id != current_user.id:
            return jsonify({"error": "not found"}), 404
        total    = job.total
        has_wa   = job.has_whatsapp
        no_wa    = job.no_whatsapp
        errors   = job.errors
        status   = job.status
        mode     = job.mode
        last_msg = job.last_message

    processed = has_wa + no_wa + errors
    pct = round(processed / max(1, total) * 100) if total else 0

    return jsonify({
        "status":       status,
        "mode":         mode,
        "total":        total,
        "has_wa":       has_wa,
        "no_wa":        no_wa,
        "errors":       errors,
        "processed":    processed,
        "remaining":    max(0, total - processed),
        "pct":          pct,
        "last_message": last_msg,
    })


# ── stop job ───────────────────────────────────────────────────────────────────

@bp.route("/job/<int:job_id>/stop", methods=["POST"])
@login_required
def stop_job(job_id):
    # Verify ownership
    job = db.session.get(ListaJob, job_id)
    if not job or job.user_id != current_user.id:
        return jsonify({"error": "not found"}), 404
    ok = request_stop(job_id)
    return jsonify({"ok": ok})


# ── download result ────────────────────────────────────────────────────────────

@bp.route("/job/<int:job_id>/download/<kind>")
@login_required
def download_result(job_id, kind):
    if kind not in ("deduped", "whatsapp", "no_whatsapp", "errors"):
        return jsonify({"error": "tipo inválido"}), 400

    job = db.session.get(ListaJob, job_id)
    if not job or job.user_id != current_user.id:
        return jsonify({"error": "not found"}), 404

    # Determine extension from original file
    ext = os.path.splitext(job.original_file)[1].lower() or ".xlsx"
    path = result_path(current_user.id, job_id, kind, ext)

    if not os.path.exists(path):
        flash("Arquivo de resultado não encontrado.", "error")
        return redirect(url_for("listas.listas_page"))

    labels = {
        "deduped":      "deduplicado",
        "whatsapp":     "com_whatsapp",
        "no_whatsapp":  "sem_whatsapp",
        "errors":       "erros",
    }
    download_name = f"lista_{labels[kind]}{ext}"
    return send_file(path, as_attachment=True, download_name=download_name)
